### ISSUE TITLE
Doesn't show anything.

### ISSUE THREAD

**Issue by pastak** [uiureo/playing#5]
[![Gyazo](https://bot.gyazo.com/d8fe5ac08ffe53d4d122730c98d25939.png)](https://gyazo.com/d8fe5ac08ffe53d4d122730c98d25939)
# Error info

[![Gyazo](https://bot.gyazo.com/136fdd26c3dabff392d06af09f067930.png)](https://gyazo.com/136fdd26c3dabff392d06af09f067930)

**Comment by uiur** [comment]
resolved in #6
